/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/huracan-falcontm-ac4bfe9c5e8d42fda5691f78e8931b95
title: Huracan Falcon™️
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lambo.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.01, 0, -0.08]} scale={0.03}>
            <group rotation={[0, 0, Math.PI / 2]} scale={[0.1, 0.1, 0.1]}>
              <group
                position={[-192.22, -1579.68, 30]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={48.67}
              >
                <mesh
                  geometry={nodes.Object_6.geometry}
                  material={nodes.Object_6.material}
                />
              </group>
              <group
                position={[-297.24, -1575.53, -648.24]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={69.7}
              >
                <mesh
                  geometry={nodes.Object_8.geometry}
                  material={nodes.Object_8.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[0, 0.01, 0]}
            rotation={[-2.83, 0, Math.PI / 2]}
            scale={[0.16, 0.16, 0.16]}
          >
            <mesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={nodes.Object_11.material}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={nodes.Object_13.material}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={nodes.Object_15.material}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={nodes.Object_17.material}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={nodes.Object_19.material}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={nodes.Object_21.material}
            />
            <mesh
              geometry={nodes.Object_22.geometry}
              material={nodes.Object_22.material}
            />
          </group>
          <group
            position={[0, 0.01, -3.03]}
            rotation={[-2.83, 0, Math.PI / 2]}
            scale={[0.16, 0.16, 0.16]}
          >
            <mesh
              geometry={nodes.Object_24.geometry}
              material={nodes.Object_24.material}
            />
            <mesh
              geometry={nodes.Object_25.geometry}
              material={nodes.Object_25.material}
            />
            <mesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
            />
            <mesh
              geometry={nodes.Object_27.geometry}
              material={nodes.Object_27.material}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={nodes.Object_28.material}
            />
            <mesh
              geometry={nodes.Object_29.geometry}
              material={nodes.Object_29.material}
            />
            <mesh
              geometry={nodes.Object_30.geometry}
              material={nodes.Object_30.material}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={nodes.Object_31.material}
            />
            <mesh
              geometry={nodes.Object_32.geometry}
              material={nodes.Object_32.material}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={nodes.Object_33.material}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={nodes.Object_34.material}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={nodes.Object_35.material}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={nodes.Object_36.material}
            />
          </group>
          <group position={[0, 0.91, 0]}>
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["Material.038"]}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials["Material.039"]}
            />
          </group>
          <group scale={[1, 0.1, 1]}>
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials["pneu.002"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_43.geometry}
              material={nodes.Object_43.material}
            />
            <mesh
              geometry={nodes.Object_44.geometry}
              material={nodes.Object_44.material}
            />
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["Material.009"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_48.geometry}
              material={nodes.Object_48.material}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={nodes.Object_49.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_51.geometry}
              material={nodes.Object_51.material}
            />
            <mesh
              geometry={nodes.Object_52.geometry}
              material={nodes.Object_52.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_54.geometry}
              material={nodes.Object_54.material}
            />
            <mesh
              geometry={nodes.Object_55.geometry}
              material={nodes.Object_55.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_57.geometry}
              material={nodes.Object_57.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_59.geometry}
              material={nodes.Object_59.material}
            />
            <mesh
              geometry={nodes.Object_60.geometry}
              material={nodes.Object_60.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_62.geometry}
              material={nodes.Object_62.material}
            />
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials["Material.010"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_65.geometry}
              material={nodes.Object_65.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_67.geometry}
              material={nodes.Object_67.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_69.geometry}
              material={nodes.Object_69.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_71.geometry}
              material={nodes.Object_71.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_73.geometry}
              material={nodes.Object_73.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_75.geometry}
              material={nodes.Object_75.material}
            />
            <mesh
              geometry={nodes.Object_76.geometry}
              material={nodes.Object_76.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_78.geometry}
              material={nodes.Object_78.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_80.geometry}
              material={nodes.Object_80.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_82.geometry}
              material={nodes.Object_82.material}
            />
            <mesh
              geometry={nodes.Object_83.geometry}
              material={nodes.Object_83.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_85.geometry}
              material={nodes.Object_85.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_87.geometry}
              material={nodes.Object_87.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_89.geometry}
              material={nodes.Object_89.material}
            />
            <mesh
              geometry={nodes.Object_90.geometry}
              material={nodes.Object_90.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_92.geometry}
              material={nodes.Object_92.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_94.geometry}
              material={nodes.Object_94.material}
            />
            <mesh
              geometry={nodes.Object_95.geometry}
              material={nodes.Object_95.material}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_97.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_99.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_101.geometry}
              material={nodes.Object_101.material}
            />
            <mesh
              geometry={nodes.Object_102.geometry}
              material={nodes.Object_102.material}
            />
          </group>
          <group position={[0, 0.09, 1.2]} scale={[0.56, 1, 1]}>
            <mesh
              geometry={nodes.Object_104.geometry}
              material={materials["Material.011"]}
            />
          </group>
          <group
            position={[0, -0.48, -0.57]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.63}
          >
            <mesh
              geometry={nodes.Object_106.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.Object_107.geometry}
              material={materials["Material.063"]}
            />
            <mesh
              geometry={nodes.Object_108.geometry}
              material={materials["Material.062"]}
            />
            <mesh
              geometry={nodes.Object_109.geometry}
              material={materials.drlwhite}
            />
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials.xenonhead}
            />
            <mesh
              geometry={nodes.Object_111.geometry}
              material={materials["Material.061"]}
            />
            <mesh
              geometry={nodes.Object_112.geometry}
              material={materials["Material.060"]}
            />
            <mesh
              geometry={nodes.Object_113.geometry}
              material={materials["Material.059"]}
            />
            <mesh
              geometry={nodes.Object_114.geometry}
              material={materials["Material.058"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_116.geometry}
              material={materials["Material.037"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lambo.gltf");
