/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lexyc16 (https://sketchfab.com/Lexyc16)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/porsche-911-930-turbo-1975-de1ffd344c41481892511f7fd332c136
title: Porsche 911 (930) Turbo 1975
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/porsche.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.09, -1.09, 1.81]} scale={[0.07, 0.04, 0.04]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
            <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[-1.09, -1.09, 1.86]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh geometry={nodes.Object_18.geometry} material={materials['Material.014']} />
          </group>
          <group position={[-1.09, -1.09, 1.86]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
          </group>
          <group position={[-1.09, -1.09, 1.86]}>
            <mesh geometry={nodes.Object_22.geometry} material={nodes.Object_22.material} />
          </group>
          <group position={[-1.09, -1.08, 1.86]}>
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[-0.78, -0.85, 0.62]} rotation={[0.59, -0.11, -0.16]} scale={0.87}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
          </group>
          <group position={[-1.7, -1.32, 1.08]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.26, 0.26, 0.26]}>
            <mesh geometry={nodes.Object_28.geometry} material={nodes.Object_28.material} />
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[-0.47, -1.32, -0.72]} rotation={[0, 0, -Math.PI / 2]} scale={[0.26, 0.27, 0.26]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
            <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          </group>
          <group position={[-1.71, -1.32, -0.72]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.26, 0.27, 0.26]}>
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
            <mesh geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
          </group>
          <group position={[-1.09, -1.09, -0.21]} scale={[0.53, 0.51, 0.83]}>
            <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          </group>
          <group position={[-0.49, -1.32, 1.08]} rotation={[0, 0, -Math.PI / 2]} scale={[0.26, 0.26, 0.26]}>
            <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
            <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
            <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} />
          </group>
          <group position={[-0.58, -0.96, 0.84]} rotation={[0.04, -0.03, -0.61]} scale={[0.06, 0.06, 0.08]}>
            <mesh geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/porsche.gltf')
